### ISSUE TITLE
[Proposal] Allow for generated `[url]` reference (not only `[url, offset, length]`)

### ISSUE THREAD

**Issue by manzt** [intake/fsspec-reference-maker#19]
### Proposal

Currently the `gen` field of V1 requires both `offset` and `length` and can only generate references of type `[url, offset, length]`. I think it would be useful to generate the `[url]` mapping, e.g:

```
  "gen": (optional, zero or more items) [
    "key": (required) jinja-str,
    "url": (required) jinja-str,
    "offset": (optional) jinja-str, // if provided, must also provide length
    "length": (optional) jinja-str,
    "dimensions": (required, one or more arbitrary keys) {
      "variable_name": (required) 
        {"start": (optional) int, "stop": (required) int, "step": (optional) int}
        OR
        [int, ...]
    }
  ],
```

### Motivation

As an example, the [DZI tile format](https://openseadragon.github.io/examples/tilesource-dzi/) is a pyramidal image format where each tile is an separate JPEG object with key `{level}/{x}_{y}.jpeg`. I have written a [napari plugin](https://github.com/manzt/napari-dzi-zarr) to translate this format to Zarr on-demand, but I experimented today with exporting this translation in some cases as an fsspec reference.

Using the `gen` field as described above let me express this translation very compactly:

```
{
  "version": "1.0",
  "templates": {
    "u": "https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/image-tiles/moon.image/moon.image_files"
  },
  "gen": [
    {
      "key": "15/{{j}}.{{i}}",
      "url": "{{u}}/15/{{i}}_{{j}}.jpeg",
      "dimensions": {
        "i": { "stop": 46 },
        "j": { "stop": 46 }
      }
   }
   ...
```

but ultimately I had [to expand the keys](https://github.com/manzt/napari-dzi-zarr/pull/9/commits/9e474938a90c2edf03a36456aa037342fdadd90e) when _writing_ the reference because this isn't spec compliant with V1.

```
{
 "version": 1,
 "templates": {
  "u": "https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/image-tiles/moon.image/moon.image_files"
 },
 "refs": {
  "15/0.0": [
   "{{u}}/15/0_0.jpeg"
  ],
  "15/1.0": [
   "{{u}}/15/0_1.jpeg"
  ],
  "15/2.0": [
   "{{u}}/15/0_2.jpeg"
  ...
```

**The former was ~3.2kb and the latter ~125kb**.

### Example

I generated a reference for [this multiscale image](http://lroc.sese.asu.edu/posts/293), converted to DZI as a deck.gl [Example](https://deck.gl/examples/tile-layer-non-geospatial/). 
 
```python
import dask.array as da
import fsspec  # 0.9.0
import napari
import zarr
from imagecodecs.numcodecs import register_codecs

from napari_dzi_zarr import DZIStore

# add image codecs to zarr registry
register_codecs()

# write the reference
# url = 'https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/image-tiles/moon.image/moon.image.dzi'
# DZIStore(url).write_fsspec(filename='moon-dzi.json')

# open references
store = fsspec.get_mapper(
    "reference://",
    fo='https://gist.githubusercontent.com/manzt/68fed819ebfbcc006e919f2c6c296972/raw/d27af0abf0d89e91652f24a64312807146772f3b/moon-dzi.json',
    target_protocol="http",
)

grp = zarr.open(store)
pyramid = [
    da.from_zarr(store, component=d["path"])
    for d in grp.attrs["multiscales"][0]["datasets"]
]

viewer = napari.Viewer()
viewer.add_image(pyramid)
napari.run()
```

![image](https://user-images.githubusercontent.com/24403730/113770349-08452a00-96f0-11eb-8752-368015c9a1d1.png)

> Note: edge tiles in DZI aren't consistently sized, so I only translate the inner tiles in the spec (meaning zarr client will fill-zero edge tiles when fetching these data)

This isn't central to my day to day work, but I assume this feature could help address the use case in https://github.com/zarr-developers/zarr-python/issues/631, where separate _objects_ can be mapped to Zarr in a predictable way.

**Comment by martindurant** [comment]
Sounds like a good idea to me
