### ISSUE TITLE
decouple hardwired source as an example?

### ISSUE THREAD

**Issue by rsignell-usgs** [intake/fsspec-reference-maker#2]
How best to handle the hardwired source example here:
https://github.com/intake/fsspec-reference-maker/blob/main/fsspec_reference_maker/hdf.py#L262-L267

**Comment by martindurant** [comment]
Working on it...

**Comment by martindurant** [comment]
Close? I left the example file there, as function `example()`, but `run()` takes parameters. I should probably add a docstring to it...

**Comment by martindurant** [comment]
Note that the script as it stands does unnecessary work, and that the output contains main redundant strings for the target file - whereas ReferenceFileSystem allows you to have a default target file for any offset where the file isn't given (null). In any case, the package could do with a CLI.

I also notice that the script currently only supports gzip compression, and I suppose there are others that will be important. This probably ought to be a new issue ( @ajelenak ) but writing it here while I remember.
