### ISSUE TITLE
C++ / pybind11 mapping for AbstractBufferedFile?

### ISSUE THREAD

**Issue by heeler** [intake/fsspec-reference-maker#23]
I maintain a library that exposes a C++ codebase as a python module. 
I'm fighting with trying to figure out how to pass the python AbstractBufferedFile into the C++ code with pybind11. 
Do you know of any projects where someone might have wrestled with this problem?
I have an ugly solution that partially works but I'm looking for something better.
Thanks!

**Comment by douglasdavis** [comment]
It might be helpful to point to your existing solution if possible!

**Comment by martindurant** [comment]
To answer the direct question: I am not aware of anyone referencing fsspec classes in C++ (or rust or ...).  

Actually, the idea of *implementing* file-systems in a compiled language with python bindings is very attractive, but I'm not aware of anyone trying to do that either.

Here is fsspec used in cython for rioxarray: https://github.com/mapbox/rasterio/pull/2141/files
and I know that `h5py` can use python file-like objects, including fsspec's, but I don't know hot that is implemented.

**Comment by heeler** [comment]
Essentially the PyObject* (the AbstractBufferedFile) is being passed in as py::handle and held onto internally. 
This seems to works to a degree but in some cases I lose the GIL possibly because the AbstactBufferedFile is closing. 

The cython link might be useful. Thanks for replying so quickly.

```
class RemoteIStream : public libCZI::IStream
{
  py::object m_abstractBufferedFile;
  std::mutex m_mutex;

public:
  explicit RemoteIStream(py::handle abstractBufferedFile)
  {
    m_abstractBufferedFile = py::reinterpret_borrow<py::object>(abstractBufferedFile);
  }

void Read(std::uint64_t offset, void* pv, std::uint64_t size, std::uint64_t* ptrBytesRead) override
{
  try {
    std::unique_lock<std::mutex> lck(m_mutex);
    m_abstractBufferedFile.attr("seek")(offset, 0);
    py::object result = m_abstractBufferedFile.attr("read")(size);
    char* buffer;
    ssize_t length;
    if (PYBIND11_BYTES_AS_STRING_AND_SIZE(result.ptr(), &buffer, &length)) {
      throw std::runtime_error("unable to convert python bytes to char *");
    }
    memcpy(pv, buffer, size);
    *ptrBytesRead = size;
  }catch(std::exception &e){
    std::cout << "exception reading file: " << e.what() << std::endl;
    throw std::runtime_error("reading failed");
  }

  ~RemoteIStream(){}

};
```
