### ISSUE TITLE
Creating reference JSONS from netCDF file on Azure Blob hangs

### ISSUE THREAD

**Issue by lsterzinger** [intake/fsspec-reference-maker#31]
I'm trying to use ReferenceMaker on files stored on Azure Blog storage after successfully doing the same for the same files on AWS S3. I'm using the following code:

```python
import fsspec
from fsspec_reference_maker.hdf import SingleHdf5ToZarr
import json

url = 'az://noaa-goes16/ABI-L2-MCMIPF/2020/002/00/OR_ABI-L2-MCMIPF-M6_G16_s20200020000216_e20200020009524_c20200020010031.nc'

so = dict(
         mode="rb", anon=True, default_fill_cache=False, default_cache_type="none",
)

with fsspec.open(url, **so, account_name='goes') as inf:
        h5chunks = SingleHdf5ToZarr(inf, url)
        with open("test.json", 'w') as outf: 
            outf.write(json.dumps(h5chunks.translate()).encode())
```

But this seems to hang forever (or at very least take longer than 20 minutes for a single file, after which I cancelled). This might be an issue with `fsspec` itself, as just opening a file with fsspec and xarray takes 10x as long on Azure as on AWS S3. See my related issue opened here https://github.com/intake/filesystem_spec/issues/681

**Comment by martindurant** [comment]
(solved by adlfs upgrade)

**Comment by lsterzinger** [comment]
Just to update here in case anyone else stumbles upon this issue: 

intake/filesystem_spec#681 did solve the problem of the slow file read times. Running the code above (except using `abfs==0.7.7`,  `goeseuwest` instead of `goes`, and writing the json in mode `'wb'` instead of `'w'`) takes ~40 seconds to generate a JSON. I chose `goeseuwest` since I am running on Microsoft Planetary Computer which is running in the West Europe region, so choosing the data hosted in the same region also serves to speed up access time. 

```python
import fsspec
from fsspec_reference_maker.hdf import SingleHdf5ToZarr
import json

url = 'az://noaa-goes16/ABI-L2-MCMIPF/2020/002/00/OR_ABI-L2-MCMIPF-M6_G16_s20200020000216_e20200020009524_c20200020010031.nc'

so = dict(
        mode="rb", anon=True, default_fill_cache=False, default_cache_type="none",
)

with fsspec.open(url, **so, account_name='goeseuwest') as inf:
        h5chunks = SingleHdf5ToZarr(inf, url)
        with open("test.json", 'wb') as outf: 
            outf.write(json.dumps(h5chunks.translate()).encode())
```
