### ISSUE TITLE
two offsets or offset + size?

### ISSUE THREAD

**Issue by rabernat** [intake/fsspec-reference-maker#4]
In most of original zarr issue discussion (https://github.com/zarr-developers/zarr-python/issues/556), offsets were specified with `offset, size`. In this spec, you are doing `start, stop`. It seems like `offset, size` will probably be slightly smaller as a text representation. I'm curious how you made that choice?

**Comment by martindurant** [comment]
I believe it was the API of the "fetch" functions littered throughout fsspec. So... mental convenience.

**Comment by manics** [comment]
I think `offset`, `size` is also less likely to cause confusion across different languages and systems. For example Python uses `inclusive-exclusive` ranges while [HTTP partial requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#Requesting_a_specific_range_from_a_server) are `inclusive-inclusive`.
