### ISSUE TITLE
"Failed to open Zarr store with consolidated metadata" xarray error with MultiZarrToZarr

### ISSUE THREAD

**Issue by lsterzinger** [intake/fsspec-reference-maker#52]
@rsignell-usgs and I ran into this when working on a notebook together yesterday, xarray seems to have a new warning when it can't open a zarr store with consolidated metadata.

When running `MultiZarrToZarr.translate()`, I get
```
/home/conda/store/578732b5a39dadc3cadc71a29a33e58ded03e8a9d5c888edac6151d80eda2868-pangeo/lib/python3.8/site-packages/fsspec_reference_maker/combine.py:170: 
RuntimeWarning: Failed to open Zarr store with consolidated metadata, falling back to try reading
non-consolidated metadata. This is typically much slower for opening a dataset. 
To silence this warning, consider:
1. Consolidating metadata in this existing store with zarr.consolidate_metadata().
2. Explicitly setting consolidated=False, to avoid trying to read consolidate metadata, or
3. Explicitly setting consolidated=True, to raise an error in this case instead of falling back to try reading non-consolidated metadata.
  dss = [xr.open_dataset(m, engine="zarr", chunks={}, **self.xr_kwargs)
  ```

I'm not sure if we're trying to consolidate metadata or not. If we are, then something isn't working. If we're not, then we might consider adding `consolidated=False` to https://github.com/intake/fsspec-reference-maker/blob/e96969d938572fb883b2acf761506dc11de45a4c/fsspec_reference_maker/combine.py#L170 to suppress the warning for now.

Minimum working code sample and [json files](https://github.com/intake/fsspec-reference-maker/files/6901854/jsons.tar.gz):

```python
import xarray as xr
import fsspec
from glob import glob
from fsspec_reference_maker.combine import MultiZarrToZarr

jsons = sorted(glob("./jsons/*"))

mzz = MultiZarrToZarr(
    jsons,
    remote_protocol='s3',
    remote_options={'anon' : 'True'},   #JSON files  
    xarray_open_kwargs={
        'decode_cf' : False,
        'mask_and_scale' : False,
        'decode_times' : False,
        'use_cftime' : False,
        'drop_variables': ['reference_time', 'crs'],
        'decode_coords' : False
    },
    xarray_concat_args={
#          "data_vars": "minimal",
#          "coords": "minimal",
#          "compat": "override",
        "join": "override",
        "combine_attrs": "override",
        "dim": "time"
    }
)

mzz.translate("test.json")
```

**Comment by martindurant** [comment]
Our reference files are *NOT* consolidated metadata in the sense given by the warning. This must be a new "feature" in xarray :)
Agree that we should set consolidated=False in the open kwargs.

**Comment by martindurant** [comment]
Which dataset are you processing here?

**Comment by lsterzinger** [comment]
This is the NWM water model dataset @rsignell-usgs has been working on, hosted at s3://noaa-nwm-retro-v2-zarr-pds

**Comment by martindurant** [comment]
OK, the same thing I was checking excessive memory use for. 
The last commit in https://github.com/intake/fsspec-reference-maker/pull/50 seems to do the right thing now. It now runs well on all 679 datasets (89GB, according to xarray "in memory" equivalent).

**Comment by martindurant** [comment]
cc @rsignell-usgs - what to do with this result?

> 'drop_variables': ['reference_time', 'crs'],

I didn't know you could do this! Makes life easier than passing a preprocessor function

> "join": "override",

None of these "minimal", "override" args should be needed any more in the PR branch, which only loads the first two files with xarray.
